version: '3.8'

services:
  churncheck-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: churncheck-api
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      # Base de datos H2
      DATABASE_URL: jdbc:h2:mem:churncheckdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      DB_DRIVER: org.h2.Driver
      DB_USERNAME: sa
      DB_PASSWORD: ""
      
      # JWT
      JWT_SECRET: c2lOJfwL7f2qyG39yoylfsuAUHdm7qxZUoOqPhe6930GkZp1fCkFhkyx4RRU5Mfuyk3y5VkqPyQrgGHts4I/0Q==
      
      # Perfil de Spring
      SPRING_PROFILES_ACTIVE: integration
      
      # Servicio ML (valores por defecto)
      ML_SERVICE_HOST: "https://mock.echoapi.com"
      ML_SERVICE_ENDPOINT: "/mock/590aa3d9c002000/predict"
      ML_API_KEY: "mock-api-key-12345"
    restart: unless-stopped
    networks:
      - churncheck-network

networks:
  churncheck-network:
    driver: bridge