spring:
  application:
    name: demo
  profiles:
    active: integration
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      # Evita que Hibernate intente crear las tablas
      ddl-auto: none 
      # Muestra las queries en consola
      show-sql: true 
      # Obligatorio para que Spring ejecute data.sql después de preparar la base
      defer-datasource-initialization: false
  security:
    token:
      # TODO: Cambiar por una variable de entorno
      secret: H12-25-L-Equipo14-DataScience
springdoc:
  api-docs:
    version: OPENAPI_3_0

# Configuración del Agente Python Local
agent:
  python:
    endpoint: http://172.17.0.1:8000  # Agente corriendo local
    timeout: 30000
    max-retries: 3

# Configuración del servicio de predicción ML
external:
  prediction:
    host: "http://localhost"
    port: 8000
    endpoint: "/predict"
    api-key: ""
    connect-timeout: 5000
    connection-timeout: 5000
    read-timeout: 10000
    max-retries: 3

