# Para test del RestClient sobre un servidor real con endpoint simulado
external:
  prediction:
    host: "https://lode.uno"
    port: 80
    endpoint: "/churncheck.php"
    connect-timeout: 4000
    connection-timeout: 4000
    read-timeout: 4000

logging:
  level:
    web: DEBUG