# Para test del RestClient sobre un servidor real con endpoint simulado
external:
  prediction:
    host: "http://40.233.25.25"
    port: 8000
    endpoint: "/predict"
    connect-timeout: 4000
    connection-timeout: 4000
    read-timeout: 4000

logging:
  level:
    web: DEBUG