spring:
  application:
    name: churncheck-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:integration}
  datasource:
    # url: jdbc:h2:mem:testdb
    url: ${DATABASE_URL}
    # driverClassName: org.h2.Driver
    driverClassName: ${DB_DRIVER}
    # username: sa
    username: ${DB_USERNAME}
    # password: ""
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      # Evita que Hibernate intente crear las tablas
      ddl-auto: none 
      # Muestra las queries en consola
      show-sql: true 
      # Obligatorio para que Spring ejecute data.sql después de preparar la base
      defer-datasource-initialization: false
  security:
    token:
      # TODO: Cambiar por una variable de entorno
      secret: ${JWT_SECRET}
springdoc:
  api-docs:
    version: OPENAPI_3_0

# Configuración del servicio de predicción ML
external:
  prediction:
    # host: "https://mock.echoapi.com"
    host: ${ML_SERVICE_HOST}
    port: 443
    # endpoint: "/mock/590aa3d9c002000/predict"
    endpoint: ${ML_SERVICE_ENDPOINT}
    # api-key: "mock-api-key-12345"
    api-key: ${ML_API_KEY}
    connect-timeout: 5000
    connection-timeout: 5000
    read-timeout: 10000
    max-retries: 3

